version: '2'
services:
  nginx:
    build:
      context: etc/nginx
      dockerfile: Dockerfile
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./var/log/nginx:/var/log/nginx
      - ./var/www:/var/www
    ports:
      - "8081:80"
    links:
      - php

  php:
    build:
      context: etc/php
      dockerfile: Dockerfile
      args:
        - WWW_DATA_UID=$WWW_DATA_UID
    environment:
      - PHP_IDE_CONFIG=$PHP_IDE_CONFIG
    volumes:
      - ./etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./var/www:/var/www
    expose:
      - "9000"
    links:
      - postgres
    command: "php-fpm -F --allow-to-run-as-root"

  postgres:
    build:
      context: etc/postgres
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD